version: '3.7'
services:
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    image: node:16
    working_dir: /usr/src/survey-clean-api
    container_name: survey_clean_api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey-api
    volumes:
      - ./dist/:/usr/src/survey-clean-api/dist/
      - ./package.json:/usr/src/survey-clean-api/package.json
    ports:
      - "3000:3000"
    links:
      - mongo