version: '3.7'
services:
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    build: .
    container_name: survey_clean_api
    restart: always
    command: npm run start
    volumes:
      - ./dist:/usr/src/survey-clean-api/dist
      - ./package.json:/usr/src/survey-clean-api/package.json
    ports:
      - "3000:3000"
    links:
      - mongo